version: "3"
services:
  node:
    build:
      context: .
      args:
        APP_HOME: ${APP_HOME}
    env_file:
      - .env
    user: node
    working_dir: $APP_HOME
    volumes:
      - ./:$APP_HOME
    ports:
      - "8080:8080"
